
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-05-13T21:45:57.837+03:00
 * Generated source version: 2.5.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Sander/Documents/Kool/Magister/2.Semester/IDU0080/4töö-workplace/BPServer/WebContent/orders.wsdl",
                      endpointInterface = "ttu.idu0080.order.server.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerId(int  customerId )*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        try {
        	List<ttu.idu0080.order.server.Order> ordersByCustomerId = new ArrayList<Order>();
        	for(Order order : Database.orders)
        		if(order.getCustomer().getCustomer() == customerId)
        			ordersByCustomerId.add(order);
        	return ordersByCustomerId;
        			
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getAllOrders(*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getAllOrders() { 
        LOG.info("Executing operation getAllOrders");
        try {
            return Database.orders;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByOrderId(int  orderId )*
     */
    public ttu.idu0080.order.server.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
        	for(Order order : Database.orders)
        		if(order.getOrderId() == orderId)
        			return order;
        	return null;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByShippingAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByShippingAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getOrdersByShippingAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-1703815329);
            _returnVal1Customer.setFirstName("FirstName-1062551228");
            _returnVal1Customer.setLastName("LastName-1132971473");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(1803011567);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(-1557775367);
            _returnVal1OrderProductsVal1.setPrice(0.80600965f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.42623562f);
            _returnVal1OrderProductsVal1.setProductCount(-1773559126);
            _returnVal1OrderProductsVal1.setProductName("ProductName1400225073");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.38413078f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(-1632327881);
            _returnVal1Seller.setName("Name824192936");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(-517696836);
            _returnVal1ShippingAddress.setCountry("Country-1491215594");
            _returnVal1ShippingAddress.setCounty("County1421106062");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-527665707");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1770657805");
            _returnVal1ShippingAddress.setZipcode("Zipcode1043890733");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerLastName(java.lang.String  lastName )*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerLastName(java.lang.String lastName) { 
        LOG.info("Executing operation getOrdersByCustomerLastName");
        System.out.println(lastName);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-1381850613);
            _returnVal1Customer.setFirstName("FirstName-1980386268");
            _returnVal1Customer.setLastName("LastName-889525083");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1795026549);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1714004068);
            _returnVal1OrderProductsVal1.setPrice(0.9498685f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.691431f);
            _returnVal1OrderProductsVal1.setProductCount(-1999601605);
            _returnVal1OrderProductsVal1.setProductName("ProductName1189973782");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.4890957f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(509453233);
            _returnVal1Seller.setName("Name-1352848386");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(651580129);
            _returnVal1ShippingAddress.setCountry("Country1283491539");
            _returnVal1ShippingAddress.setCounty("County2014756069");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-254597045");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1378567817");
            _returnVal1ShippingAddress.setZipcode("Zipcode2034971813");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
