
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ee.ttu.tud.idu0080.transport;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-05-14T00:28:35.553+03:00
 * Generated source version: 2.5.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "transport",
                      portName = "transportSOAP",
                      targetNamespace = "http://idu0080.tud.ttu.ee/transport/",
                      wsdlLocation = "file:/C:/Users/Sander/Documents/Kool/Magister/2.Semester/IDU0080/4töö-workplace/BP/WebContent/transport.wsdl",
                      endpointInterface = "ee.ttu.tud.idu0080.transport.Transport")
                      
public class TransportImpl implements Transport {

    private static final Logger LOG = Logger.getLogger(TransportImpl.class.getName());

    /* (non-Javadoc)
     * @see ee.ttu.tud.idu0080.transport.Transport#transport(java.lang.String  pakkumusId )*
     */
    public java.lang.String transport(java.lang.String pakkumusId) { 
        LOG.info("Executing operation transport");
        System.out.println(pakkumusId);
        try {
            java.lang.String _return = "_return1780485867";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
