
package ttu.idu0080.order.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-05-14T00:56:25.880+03:00
 * Generated source version: 2.5.9
 * 
 */
public final class OrderShipmentService_OrderShipmentServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.order.idu0080.ttu/", "OrderShipmentServiceService");

    private OrderShipmentService_OrderShipmentServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderShipmentServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderShipmentServiceService ss = new OrderShipmentServiceService(wsdlURL, SERVICE_NAME);
        OrderShipmentService port = ss.getOrderShipmentServicePort();  
        
        {
        System.out.println("Invoking getOrderShipmentsByOrderIdRyhmName...");
        int _getOrderShipmentsByOrderIdRyhmName_orderId = -131915439;
        java.lang.String _getOrderShipmentsByOrderIdRyhmName_ryhmName = "_getOrderShipmentsByOrderIdRyhmName_ryhmName333747943";
        java.util.List<ttu.idu0080.order.server.OrderShipment> _getOrderShipmentsByOrderIdRyhmName__return = port.getOrderShipmentsByOrderIdRyhmName(_getOrderShipmentsByOrderIdRyhmName_orderId, _getOrderShipmentsByOrderIdRyhmName_ryhmName);
        System.out.println("getOrderShipmentsByOrderIdRyhmName.result=" + _getOrderShipmentsByOrderIdRyhmName__return);


        }
        {
        System.out.println("Invoking insertOrderShipment...");
        int _insertOrderShipment_orderId = -1647620882;
        java.lang.String _insertOrderShipment_ryhmName = "_insertOrderShipment_ryhmName-1809669928";
        java.lang.String _insertOrderShipment_trackingNumber = "_insertOrderShipment_trackingNumber-245423674";
        java.lang.String _insertOrderShipment_courierName = "_insertOrderShipment_courierName-708522065";
        javax.xml.datatype.XMLGregorianCalendar _insertOrderShipment_approxDeliveryDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-14T00:56:25.927+03:00");
        double _insertOrderShipment_shippingPrice = 0.025670629277370738;
        int _insertOrderShipment__return = port.insertOrderShipment(_insertOrderShipment_orderId, _insertOrderShipment_ryhmName, _insertOrderShipment_trackingNumber, _insertOrderShipment_courierName, _insertOrderShipment_approxDeliveryDate, _insertOrderShipment_shippingPrice);
        System.out.println("insertOrderShipment.result=" + _insertOrderShipment__return);


        }

        System.exit(0);
    }

}
