package ee.ttu.tud.idu0080.bp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-05-13T20:45:14.073+03:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://idu0080.tud.ttu.ee/bp/", name = "bp")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Bp {

    @WebMethod(operationName = "TellimuseEsitamine", action = "http://idu0080.tud.ttu.ee/bp/TellimuseEsitamine")
    @WebResult(name = "MinuTellimuseVastus", targetNamespace = "http://idu0080.tud.ttu.ee/bp/", partName = "parameters")
    public MinuTellimuseVastus tellimuseEsitamine(
        @WebParam(partName = "parameters", name = "MinuTellimus", targetNamespace = "http://idu0080.tud.ttu.ee/bp/")
        MinuTellimus parameters
    );
}
